// build-host 防回归：产物 host.js 里的跨包依赖必须是「外部化裸说明符」，而不是被内联。
//
// 为什么值得一条测试（两个坏方向都不报错、只在线上发作）：发布形态下 host.js 躺在
// node_modules 里被 dsh 载入——
//   1) 内联：`@jayyuen666/dsh-plugin-shared/lib/http` 这类**子路径**说明符一旦被打进产物，shared 的
//      模块级状态就在每个插件里各复制一份；rolldown 的 external 字符串项是精确匹配，
//      只列包名会漏掉子路径，故 build-host.mjs 按「包名段」判定（该坑已在脚本注释登记）。
//   2) 残留：产物里只要还剩 `./lib/xxx.ts`，Node 载入即抛 ERR_UNSUPPORTED_NODE_MODULES_
//      TYPE_STRIPPING；而 dependencies 里跑掉一个包（如 schemastery 退回 devDependencies）
//      就会被整包内联——体积翻倍正是内联发生了的指纹，故一并钉住。
import { describe, it } from "vitest";
import assert from "node:assert/strict";
import { buildHost } from "../build-host.mjs";
import { hostFreshnessEvidence } from "./host-freshness.ts";

describe("buildHost()", () => {
  it("host.js 与最新构建逐字节一致（改 host.ts / lib/*.ts 后必须 node build-host.mjs）", async () => {
    const { pkgName, pkgDir, onDisk, built } = await hostFreshnessEvidence(import.meta.url);
    assert.equal(
      onDisk,
      built,
      onDisk === built
        ? "fresh"
        : `[${pkgName}] host.js 已过期：host.ts（或其依赖）变更后未重建。请运行：cd ${pkgDir} && node build-host.mjs`,
    );
  });

  it("产物 host.js：运行期跨包依赖保持 external（未内联）", async () => {
    const out = await buildHost();
    assert.ok(
      out.startsWith("// GENERATED by build-host.mjs"),
      "产物须带生成标记（勿手改 host.js）",
    );
    // 值导入的包必须列在 dependencies，否则被内联。
    // 0.1.7 起这份值是**宿主 fork** `@deepseek-ai/schemastery`：只有它的 resolve 会把
    // `.volatile()` 字段包成 Volatile 引用（host.ts 的十二项设置、lib/rules-namespace.ts
    // 的 rules 数组都靠它），公共 schemastery 连 `.volatile()` 方法都没有。
    assert.ok(
      out.includes('from "@deepseek-ai/schemastery"'),
      "@deepseek-ai/schemastery 必须以裸说明符留在产物里",
    );
    // 反向锁：不得退回公共 schemastery——它没有 .volatile()，解析出的仍是普通值，
    // 设置卡写进去的开关与规则卡因此永远读不到（0.1.7 迁移的根因）。
    assert.ok(
      !/from\s+["']schemastery["']/u.test(out),
      "产物不得再值导入公共 schemastery（volatile 解析只在宿主 fork 里）",
    );
    // 子路径说明符：external 字符串项匹配不到的那个坑
    assert.ok(
      out.includes('from "@jayyuen666/dsh-plugin-shared/lib/http"'),
      "shared/http 必须外部化",
    );
    assert.ok(
      out.includes('from "@jayyuen666/dsh-plugin-shared/lib/project-key"'),
      "shared/project-key 必须外部化（lib/lesson-store.ts 的 project 单源）",
    );
    assert.ok(
      out.includes('from "@deepseek-ai/dsh-brand"'),
      "dsh-brand 必须外部化（口径 A；内联=把官方 branded-string 构造器复制进本包产物）",
    );
    assert.ok(!/^function brandString\(/mu.test(out), "产物不得内联 brandString 的函数体");
    assert.ok(
      out.includes('from "@jayyuen666/dsh-plugin-shared/lib/record"'),
      "shared/record 必须外部化（SP-D 起 isRecord/fieldOf 是跨包单点，内联=每个插件各持一份）",
    );
    assert.ok(
      out.includes('from "@jayyuen666/dsh-plugin-shared/lib/jsonl"'),
      "shared/jsonl 必须外部化（对半收缩判据与 ctx-observe 同源；写盘与内部 catch 留本包）",
    );
  });

  it("产物 host.js：不残留 ./x.ts 形态的相对说明符", async () => {
    const out = await buildHost();
    // lib/*.ts 应已被吃进单文件；留着即"发布后 Node 直接拒载"的形态
    assert.ok(!/["']\.\/[^"']*\.ts["']/u.test(out), "不得有 ./x.ts 说明符残留");
  });
});

describe("闸门的外部化面（shared/lib/trust）", () => {
  it("lib/trust 子路径保持裸说明符，且 guardTrust 的实现未被内联", async () => {
    // 这些包原先只钉了 http/project-key/record/jsonl 几枚子路径，`lib/trust` 是新增的第四个坑位：
    // external 的字符串项是精确匹配，子路径一旦漏掉就把整份判据复制进本包产物（判据分叉的起点）。
    const out = await buildHost();
    assert.ok(
      out.includes('from "@jayyuen666/dsh-plugin-shared/lib/trust"'),
      "shared/trust 必须外部化",
    );
    assert.ok(!/^function guardTrust\(/mu.test(out), "产物不得内联 guardTrust 的函数体");
  });
});
