// test/log-templates.ts —— 本包算子可见日志的模板片段（由源码扫出，勿手改）。
// 账本用它判「这条日志是不是源码里现存的模板」；新增 console.* 若没有对应片段，
// 跑测时那条日志就会被判未认领（见 test/setup-logs.ts）。这里不读盘：规则面
// （node/no-sync 等）不该为了测试脚手架开口子，且模板漂移应当是一次显式的改动。
export const LOG_TEMPLATES: readonly string[] = [
  '" 不可用（非空但超',
  '.rules" is not an array — rule library reads empty and refuses writes (switches still work)',
  ": session settled for project",
  "[lesson-loop] armed rule violated:",
  "[lesson-loop] candidate ready for review:",
  "[lesson-loop] commands service unavailable — /lessons-digest not registered",
  "[lesson-loop] ctx.provide unavailable — lessonLoop service invisible to reporters",
  "[lesson-loop] decay failed:",
  "[lesson-loop] decay:",
  "[lesson-loop] fragment migration failed:",
  "[lesson-loop] injected",
  "[lesson-loop] lesson append failed:",
  '[lesson-loop] lesson source "',
  "[lesson-loop] migrated",
  "[lesson-loop] normalized",
  "[lesson-loop] pass failed:",
  "[lesson-loop] project key migration failed:",
  "[lesson-loop] report failed:",
  "[lesson-loop] rule-action handler failed:",
  '[lesson-loop] rules namespace rejected: "',
  "[lesson-loop] rules read failed:",
  "[lesson-loop] rules write failed:",
  "[lesson-loop] session-start inject failed:",
  "[lesson-loop] settings provider has no CAS surface — rule library unavailable (switches still work)",
  "armed rule(s) for project",
  "demoted,",
  "fragment rule(s) to stable signatures",
  "malformed lesson line(s) skipped in",
  "passed rule(s))",
  "rule project key(s)${merged > 0 ?",
  "undeterminable",
  "字符），按 manual 记账",
  "（violation=",
];
