#!/usr/bin/env node
/// <reference types="node" />
// 顶部 node reference：oxlint 类型检查对 .mjs 不自动加载 @types/node，需显式声明
// 才能解析 node:fs/promises / node:path / process / import.meta（否则整文件按 error
// 类型误报 no-unsafe-*），与同仓 zvec-grep / ocr-review 的 build-client.mjs 一致。
// 构建 client.js：rolldown 把 src/client-entry.ts 打包为 CJS（react 外部化），再包进
// window.__ModuleLoader__.load({ id, factory }) UMD 外壳（session-rescue 同款）。
// 运行：node build-client.mjs（或 npm run build:client）。buildClient() 供测试导入。
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { rolldown } from "rolldown";
import { canonicalizeRegionPaths } from "@jayyuen66/dsh-plugin-shared/lib/canonicalize-region-paths";

const root = import.meta.dirname;

/** @type {unknown} */
const pkgJson = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));

/**
 * 从 JSON.parse 的 unknown 投影为 Record（非对象 → 空对象兜底），避免 any 索引。
 * @param {unknown} raw
 * @returns {Record<string, unknown>}
 */
function asRecord(raw) {
  if (raw !== null && typeof raw === "object" && !Array.isArray(raw)) {
    return raw;
  }
  return {};
}

// 模块表 id 必须等于包名：dsh 的 client-modules 只扫裸包名条目并按包名建键，
// 写死字符串会在改名/换装法下静默不渲染卡片（与其余包的 build-client 同口径）。
const nameKey = "name";
const nameRaw = asRecord(pkgJson)[nameKey];
const pkgName = typeof nameRaw === "string" ? nameRaw : "unknown";

/** 生成 client.js 的完整文本（含 ModuleLoader 外壳）。 */
export async function buildClient() {
  const bundle = await rolldown({
    input: path.join(root, "src", "client-entry.ts"),
    external: ["react"],
    platform: "browser",
    resolve: {
      extensions: [".ts", ".mjs", ".js", ".json"],
    },
  });
  const { output } = await bundle.generate({
    format: "cjs",
  });
  const chunk = output.find((item) => item.type === "chunk");
  if (chunk === undefined) {
    throw new Error("rolldown generate returned no chunk output");
  }
  // 见 shared/lib/canonicalize-region-paths.ts：`//#region` 行的路径由 rolldown 按 process.cwd()
  // 算出 ⇒ 同一份源码两种字节。折 canonical 必须落在返回值之前（test/client-freshness.ts 逐字节
  // 比内存构建与磁盘产物），不能只在 writeFile 那一侧做。
  const body = canonicalizeRegionPaths(chunk.code.trimEnd(), root);
  return [
    "// GENERATED by buildClient() in build-client.mjs — edit src/*.ts, then run `node build-client.mjs`.",
    "window.__ModuleLoader__.load({",
    `  id: '${pkgName}',`,
    "  factory: (require) => {",
    "    var module = { exports: {} };",
    "    var exports = module.exports;",
    body,
    "    return module.exports;",
    "  },",
    "});",
    "",
  ].join("\n");
}

async function main() {
  const out = await buildClient();
  await writeFile(path.join(root, "client.js"), out, "utf8");
  console.info("client.js written:", out.length, "chars");
}

if (process.argv[1] === import.meta.filename) {
  try {
    await main();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}
